# Production configuration for GitHub Pages
baseurl: '/narratives-in-the-wild/'
url: 'https://maria-antoniak.github.io'
permalink: pretty
title: 'Narratives in the Wild'

# Minimal configuration for GitHub Pages compatibility
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections
collections:
  research:
    output: true
    permalink: /:collection/:name/
  team:
    output: true
    permalink: /:collection/:name/

# Defaults
defaults:
  - scope:
      path: ""
      type: "research"
    values:
      layout: "research-item"
  - scope:
      path: ""
      type: "team"
    values:
      layout: "team"

# Plugins (only GitHub Pages supported ones)
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - LICENSE
  - README.md
  - _config_prod.yml